### ISSUE TITLE
Can receive more events than the max_events parameter passed in

### ISSUE THREAD

**Issue by RichardWarburton** [sadiqj/ocaml#7]
You can try the current opsian agent as a reproducer (commit 98799f79c3e896128374a001ba19637fe470ca95). I'm passing in 5000 as a max events parameter and poll() can return far more events, eg: 130247. You'll probably hit it on the fist poll.

**Comment by sadiqj** [comment]
After some headscratching, I know what the cause of this is.

**Comment by sadiqj** [comment]
This is fixed.
